### ISSUE TITLE
Avoid glob imports from top-level of crate

### ISSUE THREAD

**Issue by eternaleye** [anima-engine/mrusty#85]
It's generally considered best practice to put "recommended" glob imports into a `prelude` module (`std::io::prelude`, `iron::prelude`, etc.) so that the user would write

``` Rust
extern crate mrusty;
use mrusty::prelude::*;
```

rather than

``` Rust
extern crate mrusty;
use mrusty::*;
```

**Comment by dragostis** [comment]
I'll prep this and a few other small details for a future release, most probably to coincide with Rust's 1.9.0 release. Thanks for feedback! 👍

**Comment by dragostis** [comment]
For now, the number of possible imports does not mandate a `prelude` solution. I'm going to close this issue until either that changes or a stronger argument arises.
