### ISSUE TITLE
Is there a way to put class macro definitions in separate modules?

### ISSUE THREAD

**Issue by Qard** [anima-engine/mrusty#88]
I tried moving some `mrusty_class!(...)` macros to separate files, but nothing gets the `pub` keyword applied to it, so it's all inaccessible from other modules.

**Comment by dragostis** [comment]
I don't really understand what you mean. `mrusty_class!` doesn't define anything in Rust, only in mruby.

**Comment by Qard** [comment]
The trait implementation that `mrusty_class!(...)` transforms to does not include the `pub` keywords on the functions, so if you try to split up your `mrusty_class!(...)` usage into separate files, the trait function are inaccessible.

**Comment by dragostis** [comment]
Which function are you talking about? Could you give me a simple example?

**Comment by Qard** [comment]
This right here: https://github.com/anima-engine/mrusty/blob/master/src/macros.rs#L741-L774

The `require` fn declarations need `pub` keywords, or you can't define classes in separate files from where you use them.

**Comment by dragostis** [comment]
You cannot make trait methods public: they already are as long as you import the Trait. If you add `pub` you'll get `unnecessary visibility qualifier`.

What you probably want is to `use MrubyFile`. It might be a good idea to have a `prelude` module with the usual imports.

**Comment by Qard** [comment]
Ah, yep. That's what it was. I need a `use mrusty::*` at the top of the file.

Don't mind me, just being a Rust newbie over here. 😜

**Comment by dragostis** [comment]
No prob. Sorry for the late reply.

Hope you enjoy using Rust and let me know if there's anything you think mrusty can do better.
