### ISSUE TITLE
Call Rust functions with Ruby blocks

### ISSUE THREAD

**Issue by vktec** [anima-engine/mrusty#89]
Currently, to allow a Rust function to accept a block, I have to write the Rust function, have it accept a `Value` and write a wrapper for that function in Ruby, that accepts a block and passes it to the underlying Rust function as a Proc, which can then be called using `my_proc.call("call", Vec::new()).unwrap()`.

This seems a little hacky, so either I'm missing something or this could do with being implemented.

**Comment by dragostis** [comment]
Definitely a valid use case. The [& block signature](https://github.com/mruby/mruby/blob/master/include/mruby.h#L733) has to be added to the [sig sub-macro](https://github.com/anima-engine/mrusty/blob/master/src/macros.rs#L153). Then, there's need for some special syntax for blocks in [defines](https://github.com/anima-engine/mrusty/blob/master/src/macros.rs#L358). Maybe actually adding a special `Block` type in Rust?

**Comment by vktec** [comment]
I'm not sure there's any need for a `Block` type. `Value`s can already be [`Proc`](http://ruby-doc.org/core-2.3.1/Proc.html)s, which is what blocks are converted to when passed to Ruby functions:

```ruby
def foo(&block)
  puts block.class
end

foo {} # Outputs "Proc"
```

**Comment by dragostis** [comment]
Of course. What I was trying to hint af was the fact that the Rust method definition macro would need a way to know that a certain argument it receives is a block, analogous to Ruby's `&` if you may. This is why introducing `Block` might make sense.

**Comment by vktec** [comment]
It would be nice if the `mrfn!` macro could use the `&` syntax (which could work, since reference parameters must be surrounded with parentheses anyway), and it looks like the output function definition uses `mrb_get_args` to get arguments, so I don't _think_ an extra type is necessary.

Here's an example of what using the `mrfn!` macro could look like:

```rust
mrfn!(|mruby, _slf: Value, a: i32, b: i32, &block| {
    ...
});
```

**Comment by dragostis** [comment]
I'll have a look.

**Comment by dragostis** [comment]
The problem with `&block` is that each value in the arguments list needs to be a single token for the macro to be relatively simple which is why composed tokens are surrounded by parens. This is why I first considered adding a type `arg: Block` since it seems to be the only explicit and relatively simple way to do it.

**Comment by vktec** [comment]
Ah, fair enough. A `Block` type sounds like the best way to go about this then.

**Comment by dragostis** [comment]
@vktec Do you need the feature soon? I've got a semi-complete implementation that is not yet working, but I've discovered a bug riddle everywhere in the library that will be noticeable once the next version of Rust is out. So I'm trying to get that fixed before adding this feature. I should have a working PR for this in a couple of days or so.

**Comment by vktec** [comment]
No, there's no rush. I can just write a method in Ruby that accepts a block and passes it along to the underlying Rust method for now.

**Comment by dragostis** [comment]
@vktec I'm planning to merge the PR tomorrow morning (UTC). You can take a look if you want to. In the meantime, I'll try to figure out the memory leak. (#90)
