### ISSUE TITLE
Don't require glob import to use mrfn! et al

### ISSUE THREAD

**Issue by AndyBarron** [anima-engine/mrusty#92]
The $crate variable automatically expands to your module global path (i.e. `::mrusty`), so that can be used to make mrusty's macros hygienic. This is a major issue, because requiring glob imports for macros to work is considered very bad practice in Rust-land.

I may attempt a PR for this, if I have the time.

**Comment by dragostis** [comment]
@AndyBarron I agree. Thanks for the issue. There's definitely a lot of room for improvement when it comes to macros here. I'd be more than happy to see a PR. 👍

**Comment by AndyBarron** [comment]
Since this already only works on Beta... Is there strong opposition to only work on Nightly?

Reasoning: When refactoring the `@init` and `@sig` macros, I'm trying to make it so that the left side doesn't match on the *exact* type name - in other words, you could pass in typedefs or full type paths and it would work fine. This is obviously a huge win for ergonomics and hygiene. It's also important because we need to initialize different structs and provide different sigs based on the type.

*However*, the only sane way of doing that is using trait specialization, which is not yet stabilized. (I guess we could theoretically use `Any` and try downcasting to every concrete types, but that feels *gross*.)

**Comment by dragostis** [comment]
It actually does work on stable ever since 1.9.0 came out. (I should probably just remove that notice on the readme)

Working on stable is definitely something that I would like to keep. I guess specialization is going to be stabilized *somewhat* soon? Compared to procedural macros, anyway.

Do you have a concrete example for this?

**Comment by AndyBarron** [comment]
As a reduced example, in `macros.rs`, we have these rules for `mrfn!`:

```
( @init $name:ident, bool )   => (let $name = ::std::mem::uninitialized::<bool>(););
( @init $name:ident, Value )  => (let $name = ::std::mem::uninitialized::<$crate::MrValue>(););
```

Since we're matching on the *exact* name of the type (i.e. `"bool"` and `"Value"`), this will not work if e.g. we use `mrusty::Value` (fully qualified path), or if we typedef `bool` to `boolean` (dumb example, but you get the idea).

What I've done is created the following trait:

```
pub trait RubyInit {
    type Init;
}
```

And reduced the rule to this:

```
( @init $name:ident, $t:ty ) => (let $name: <$t as $crate::RubyInit>::Init = ::std::mem::uninitialized(););
```

So, as long as you pass in a type `$t` that implements `RubyInit`, you're golden. Cleaner macros, better type checking.

*But*... We want `RubyInit` to have `type Init = Self` for `i32`, `f64`, and `bool`; `type Init = *const c_char` for `&str`; and `type Init = mrusty::MrValue` for **all other types**. That's the part that requires specialization.

I definitely respect wanting this to work on stable, so I *might* be able to finagle something using `std::any::Any`; but, now that I think of it, it probably won't work for this case. Could be worth a shot, though.

**Comment by dragostis** [comment]
An implementation with `Any` should work since you'll always be return the same type. (`RubyInit`)

This should make things much easier for the macro's implementations too.

This shouldn't be needed once procedural macros are out though. The way I see it, once they are actually out, parsing the args manually and then making use of specialization is the way to go. Also, this would make sense for a 1.0 release.

**Comment by dragostis** [comment]
By the way, any idea how to fix #90? There's a [minimal example](https://github.com/mruby/mruby/issues/3233#issuecomment-260042889) on mruby.

**Comment by AndyBarron** [comment]
Well, the `@init` rules currently instantiate different types, and an implementation using `Any` would be tough because it would have a different return type for each possible arg type... But maybe I can hack it together with macros.

I'll drop a comment on the other issue; I don't have a solution (don't know much about (m)Ruby) but might have a workaround for the Rust binding?

**Comment by AndyBarron** [comment]
About to submit a pull request that sanitizes all the macro *expansions.* Cleaning up the matching rules themselves is worthy of a separate issue, I think.

**Comment by dragostis** [comment]
@AndyBarron I agree!
