### ISSUE TITLE
"error: no rules expected the token ..." when using mrfn! with Value parameters.

### ISSUE THREAD

**Issue by vktec** [anima-engine/mrusty#93]
I may well be missing something, but the following code raises an error for me:

```rust
#[macro_use]
extern crate mrusty;
use mrusty::*;

struct Foo(value);

fn main() {
    let mrb = Mruby::new();
    mrb.def_class_for::<Foo>("Foo");
    mrb.def_method_for::<Foo, _>(
        "initialize",
        mrfn!(|_mrb, slf: Value, x: Value| {
            slf.init(Foo(x))
        }));
}
```

Here's the error

```
error: no rules expected the token `x`
   --> <mrusty macros>:136:19
    |
136 | @ init $ ( $ name : $ t ) , * ) ; let mrb = $ mruby . borrow (  ) . mrb ; let
    |                   ^
```

Any insights on either what I'm doing wrong or what this issue could be?

**Comment by dragostis** [comment]
It's solved on master. I was planning on doing a release when the memory leak is dealt with, so you wan use the tip of tree in Cargo until then.

**Comment by dragostis** [comment]
Also, I would recommend using the `mrusty_class!` macro instead.

**Comment by vktec** [comment]
Thanks @dragostis, it works perfectly from `master`. I forgot about `mrusty_class!`, that makes things a lot prettier.
